### ISSUE TITLE
Problem running LazyLibrarian in docker to find the ebook dir

### ISSUE THREAD

**Issue by microSoftware** [lazylibrarian/LazyLibrarian#53]
### LazyLibrarian version number (at the bottom of config page)
version-0ca9b70c

### Operating system used (windows, mac, linux, NAS type)
Ubuntu
### Interface in use 

> Client: Docker Engine - Community
>  Version:           26.0.0
>  API version:       1.45
>  Go version:        go1.21.8
>  Git commit:        2ae903e
>  Built:             Wed Mar 20 15:17:56 2024
>  OS/Arch:           linux/amd64
>  Context:           default
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          26.0.0
>   API version:      1.45 (minimum version 1.24)
>   Go version:       go1.21.8
>   Git commit:       8b79278
>   Built:            Wed Mar 20 15:17:56 2024
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.6.28
>   GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
>  runc:
>   Version:          1.1.12
>   GitCommit:        v1.1.12-0-g51d5e94
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
 

i've set correctly the volume environment /ebook and /books to the host path /DATA/Media/Books
I've set both because i didn't know either it was "ebook" or "books" so i set both just in case.

I added pdf ebookss inside my host directory /DATA/Media/Books. 
The permission of those files are not root.

When i click on the scan button in LazyLibrarian. It doesn't find it. And in the log i have this:

`2024-04-19 00:52:39,318 WARNING: eBook dir [''] not found, using /config [filesystem.py:608 (EBOOK_SCAN)]`

So i'm not sure where the problem lie because it seems i have set all the config right.

**Comment by orangewhipster** [comment]
I have the exact same issue. I get "eBook dir [''] not found" and I've tried all the different options I could find out there and nothing works.

Using LL in Unraid using linuxserver.io repository.

**Comment by orangewhipster** [comment]
....and I just figured it out!!

Inside the config settings for LL, you need to go to "Interface" and check "Show eBooks". Then you can go to the "processing" tab and there will be a spot to put in your eBooks folder. In my case I just put in "/books" as that is what I had set up as a Path in Unraid for that folder.

Because I was only using LL for magazines and not books, I just unchecked anything to do with books, but the path is needed for LL to know where to move the files to once they are in the downloads folder.
